#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ─────────────────────────────────────────────────────────────
# ПАТЧ: patch_executor.py
# Исполнитель (A09) замыкает петлю — рука открывающая + летописец
# Версия: 1.0 · 2026-06-19 · Брат (Claude) + Шеф
#
# ЧТО ДЕЛАЕТ (идемпотентно, маркеры + авто-бэкап):
#   1. Кладёт движок executor_live.py (EXECUTOR_ENGINE_V1):
#      · РУКА ОТКРЫВАЮЩАЯ (код) — позиции в trading_state["positions"]
#        ПО ФАКТУ ТАБЛО (direction/entry/stop/lot от трейдера). PAPER.
#      · РУКА-ЛЕТОПИСЕЦ (LLM) — execution_log + history_dna + task_score.
#      Защита чисел: позиции из табло, не из слов LLM (как Архивариус).
#   2. Перезаписывает A09/forge/prompt.md под Закон (табло вместо
#      chain_data, снят хард-стоп, убран tp, до v1.8). Старый → .bak.
#   3. Врезает Исполнителя в кнопку РЫНОК (после трёх трейдеров) и в
#      tester_express (после Консерватора), + чат-пузырёк A09.
#
#   Петля: sensors → traders (табло) → ИСПОЛНИТЕЛЬ (позиции открыты) →
#   следующий бар: _settle закрывает по стопу/exit_bell → PnL в R.
#
# Требует: avan_live/cons_live уже на месте; фикс direction применён
#   (patch_fix_direction) — иначе шорты закроются как лонги.
# Запуск из КОРНЯ репы:  python patch_executor.py
# ─────────────────────────────────────────────────────────────
import base64, shutil, sys, py_compile
from datetime import datetime
from pathlib import Path

ROOT = Path.cwd()
TRADING = ROOT / "studio" / "modules" / "trading"
UI      = ROOT / "studio" / "economy" / "ui_exchange.py"
TESTER  = TRADING / "tester_express.py"
MOD     = TRADING / "executor_live.py"
PROMPT  = TRADING / "A09" / "forge" / "prompt.md"

BTN_ANCHOR = '                update_chat_display()\n                update_avatar_states()\n\n    # ── Подсветка активного пузырька ─────────────────────────\n'

BTN_NEW = '                update_chat_display()\n                update_avatar_states()\n\n            # ═══════════════════════════════════════════════════\n            # ИСПОЛНИТЕЛЬ САДИТСЯ — A09 замыкает петлю\n            # [EXECUTOR врезан патчем patch_executor]\n            # ───────────────────────────────────────────────────\n            # Трое трейдеров сказали своё (табло накрыто). Исполнитель:\n            # КОД открывает позиции по факту табло (PAPER), LLM пишет\n            # летопись (execution_log + history_dna + task_score). PnL\n            # посчитает _settle на следующем баре. Круг замыкается.\n            ui.notify("📋 Исполнитель замыкает петлю...", type="info")\n            try:\n                from studio.modules.trading.executor_live import run_executor\n                rex = await asyncio.get_event_loop().run_in_executor(\n                    None, lambda: run_executor(symbol="XAUUSD", timeframe="H4"))\n            except Exception as e:\n                rex = {"ok": False, "error": str(e)}\n\n            if rex.get("ok"):\n                esig = rex.get("signal", {})\n                fdna = esig.get("final_dna", {})\n                sent = fdna.get("orders_sent", "—")\n                tsk  = fdna.get("task_score", "—")\n                state["reports"]["A09"] = (\n                    rex.get("narrative", "")\n                    + "\\n\\n— Летопись: " + esig.get("history_dna", ""))\n                state["executor_signal"] = esig\n                state["executor_stats"]  = rex.get("stats", {})\n                state["executor_last_run"] = {\n                    "narrative": rex.get("narrative", ""),\n                    "signal":    esig,\n                    "market":    rex.get("market", {}),\n                }\n                line = (f"📋 Исполнитель: ордеров {sent} из 3 · "\n                        f"task_score {tsk}. {esig.get(\'history_dna\',\'\')}")\n                ui.notify(f"📋 Исполнитель: {sent} из 3", type="positive")\n                state["chat_history"].append({\n                    "role": "assistant", "agent": "A09", "content": line})\n                update_chat_display()\n                update_avatar_states()\n            else:\n                ui.notify(f"📋 Исполнитель: сбой — {rex.get(\'error\',\'?\')}",\n                          type="warning")\n\n    # ── Подсветка активного пузырька ─────────────────────────\n'

TST_ANCHOR = '                out(f"  🛡 КОНСЕРВАТОР: сбой — {rco.get(\'error\',\'?\')}")\n            out("")\n\n            if caught >= n_signals:\n'

TST_NEW = '                out(f"  🛡 КОНСЕРВАТОР: сбой — {rco.get(\'error\',\'?\')}")\n            out("")\n\n            # ИСПОЛНИТЕЛЬ — A09 замыкает петлю (открывает по факту табло)\n            # [EXECUTOR врезан патчем patch_executor]\n            from studio.modules.trading.executor_live import run_executor\n            rex = run_executor(symbol=symbol, timeframe=timeframe)\n            if rex.get("ok"):\n                esig = rex.get("signal", {})\n                fdna = esig.get("final_dna", {})\n                out(f"  📋 ИСПОЛНИТЕЛЬ: ордеров "\n                    f"{fdna.get(\'orders_sent\',\'—\')} из 3 · "\n                    f"task_score {fdna.get(\'task_score\',\'—\')}")\n                if esig.get("history_dna"):\n                    out(f"     └─ летопись: {esig.get(\'history_dna\',\'\').strip()}")\n            else:\n                out(f"  📋 ИСПОЛНИТЕЛЬ: сбой — {rex.get(\'error\',\'?\')}")\n            out("")\n\n            if caught >= n_signals:\n'

CHAT_ANCHOR = '        if agent_id in ("A06", "A07", "A08"):\n            _tmap = {\n                "A06": ("brut_live", "chat_with_brut", "brut_last_run", "🪨", "Брут"),\n                "A07": ("avan_live", "chat_with_avan", "avan_last_run", "🎲", "Авантюрист"),\n                "A08": ("cons_live", "chat_with_cons", "cons_last_run", "⚖️", "Консерватор"),\n            }\n'

CHAT_NEW = '        if agent_id in ("A06", "A07", "A08", "A09"):\n            _tmap = {\n                "A06": ("brut_live", "chat_with_brut", "brut_last_run", "🪨", "Брут"),\n                "A07": ("avan_live", "chat_with_avan", "avan_last_run", "🎲", "Авантюрист"),\n                "A08": ("cons_live", "chat_with_cons", "cons_last_run", "⚖️", "Консерватор"),\n                "A09": ("executor_live", "chat_with_executor", "executor_last_run", "📋", "Исполнитель"),\n            }\n'

EXEC_MOD_B64 = (
    'IyBzdHVkaW8vbW9kdWxlcy90cmFkaW5nL2V4ZWN1dG9yX2xpdmUucHkKIyDilIDilIDilIDilIDi'
    'lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi'
    'lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi'
    'lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAK'
    'IyDQltCY0JLQntCZINCf0KDQntCT0J7QnSDQmNCh0J/QntCb0J3QmNCi0JXQm9CvIChBMDkpIOKA'
    'lCDRgNGD0LrQsCDRhtC10YXQsCwg0LfQsNC80YvQutCw0LXRgiDQv9C10YLQu9GOCiMgRVhFQ1VU'
    'T1JfRU5HSU5FX1YxIMK3INCS0LXRgNGB0LjRjzogMC4xIMK3IDIwMjYtMDYtMTkKIwojINCk0L7R'
    'gNC80LAg4oCUINCx0LvQuNC30L3QtdGGINC00LLQuNC20LrQvtCyLCDQndCeINC/0YDQuNGA0L7Q'
    'tNCwINGC0YDQtdGC0YzRjy4g0J3QtSDRgdC10L3RgdC+0YAgKNC60LvQsNC00ZHRgiDRhNCw0LrR'
    'giksCiMg0L3QtSDRgtGA0LXQudC00LXRgCAo0YDQtdGI0LDQtdGCKS4g0JjRgdC/0L7Qu9C90LjR'
    'gtC10LvRjCDQmNCh0J/QntCb0J3Qr9CV0KIg0Lgg0JLQldCU0IHQoiDQm9CV0KLQntCf0JjQodCs'
    'LiDQlNCd0Jo6CiMg0LDQstGC0L7QvdC+0LzQuNGPIDAuMCwg0Y3QvNC/0LDRgtC40Y8gMC4wNSDi'
    'gJQgwqvQptC10LvRjCDQstC40LbRgy4g0JjRgdC/0L7Qu9C90Y/RjsK7LiDQndC1INGB0YPQtNC4'
    '0YIg0YDRi9C90L7Qui4KIwojINCU0JLQlSDQoNCj0JrQmCDQoNCQ0JfQndCe0Jkg0J/QoNCY0KDQ'
    'ntCU0Ks6CiMgICAxLiDQoNCj0JrQkCDQntCi0JrQoNCr0JLQkNCu0KnQkNCvICjQmtCe0JQsINC0'
    '0L4gTExNKS4g0KfQuNGC0LDQtdGCINGC0LDQsdC70L4g0YLRgNC+0LjRhSDRgtGA0LXQudC00LXR'
    'gNC+0LIuCiMgICAgICDQlNC70Y8g0LrQsNC20LTQvtCz0L4gQVBQUk9WRUQg0LrQu9Cw0LTRkdGC'
    'INC/0L7Qt9C40YbQuNGOINCyIHRyYWRpbmdfc3RhdGVbInBvc2l0aW9ucyJdCiMgICAgICDQn9Ce'
    'INCk0JDQmtCi0KMg0KLQkNCR0JvQniAoZGlyZWN0aW9uL2VudHJ5L3N0b3AvbG90INC+0YIg0YLR'
    'gNC10LnQtNC10YDQsCkg4oCUINC90LUg0LjQtwojICAgICAg0YHQu9C+0LIgTExNLiDQlNC10L3R'
    'jNCz0Lgg0L3QtSDQvNC10YHRgtC+INC00LvRjyDQs9Cw0LvQu9GO0YbQuNC90LDRhtC40LkgKNC3'
    '0LDRidC40YLQsCDRh9C40YHQtdC7LCDQutCw0Log0YMKIyAgICAgINCQ0YDRhdC40LLQsNGA0LjR'
    'g9GB0LApLiBQQVBFUi3RgNC10LbQuNC8LiDQlNC40YHRhtC40L/Qu9C40L3QsDog0L3QtSDQtNGD'
    '0LHQu9C40YDRg9C10YIg0YPQttC1INC+0YLQutGA0YvRgtGL0LkKIyAgICAgIG1hZ2ljLiDQl9Cw'
    '0LrRgNGL0YLQuNC1IOKAlCDQndCVINC10LPQviDQtNC10LvQviwgX3NldHRsZV9wb3NpdGlvbnMg'
    '0LTQtdC70LDQtdGCINGB0LDQvNC+LgojICAgMi4g0KDQo9Ca0JAt0JvQldCi0J7Qn9CY0KHQldCm'
    'IChMTE0sINC10LPQviDQs9C+0LvQvtGBKS4g0J/QvtC70YPRh9Cw0LXRgiDRgtCw0LHQu9C+ICsg'
    '0LHQsNGALCDQv9C40YjQtdGCCiMgICAgICBleGVjdXRpb25fbG9nICjQtdCz0L4g0L/QvtC00L/Q'
    'uNGB0YwpLCBoaXN0b3J5X2RuYSAo0L7QtNC90LAg0YHRgtGA0L7QutCwINC/0YDQsNCy0LTRiyks'
    'CiMgICAgICB0YXNrX3Njb3JlICjRh9C10YHRgtC90LDRjyDQvtGG0LXQvdC60LAg0JTQmNCh0KbQ'
    'mNCf0JvQmNCd0Ksg0YbQtdGF0LAsINC90LUg0L/RgNC40LHRi9C70Lgg0YDRi9C90LrQsCkuCiMK'
    'IyDQl9CQ0KnQmNCi0JAg0KfQmNCh0JXQmzog0L/QvtC30LjRhtC40Lgg0LIgc3RhdGUg0LrQu9Cw'
    '0LTRkdGCINCa0J7QlCDQuNC3INGC0LDQsdC70L4uIGV4ZWN1dGlvbl9sb2cg0L7RggojIExMTSDi'
    'gJQg0LvQtdGC0L7Qv9C40YHRjCwg0LzQvtC20LXRgiDRgdC+0LTQtdGA0LbQsNGC0Ywg0LXQs9C+'
    'INCy0LfQs9C70Y/QtCwg0L3QviDQvdCwINGE0LjQt9C40LrRgyDQvdC1INCy0LvQuNGP0LXRgi4K'
    'IyDQldGB0LvQuCBMTE0g0L3QsNCy0YDQsNC7INGH0LjRgdC70LAg0LIgbG9nIOKAlCDQv9C+0LfQ'
    'uNGG0LjRjyDQstGB0ZEg0YDQsNCy0L3QviDQvtGC0LrRgNGL0YLQsCDQv9C+INGE0LDQutGC0YMg'
    '0YLQsNCx0LvQvi4KIwojINCf0JXQotCb0K86IHNlbnNvcnMg4oaSIHRyYWRlcnMgKNGC0LDQsdC7'
    '0L4pIOKGkiDQmNCh0J/QntCb0J3QmNCi0JXQm9CsICjQv9C+0LfQuNGG0LjQuCDQvtGC0LrRgNGL'
    '0YLRiykg4oaSCiMg0YHQu9C10LTRg9GO0YnQuNC5INCx0LDRgDogX3NldHRsZSDQt9Cw0LrRgNGL'
    '0LLQsNC10YIg0L/QviDRgdGC0L7Qv9GDL2V4aXRfYmVsbCDihpIgUG5MINCyIFIuINCa0YDRg9Cz'
    'INGG0LXQuy4KIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi'
    'lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi'
    'lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi'
    'lIDilIDilIDilIDilIDilIDilIDilIAKCmltcG9ydCBqc29uCmltcG9ydCByZQppbXBvcnQgdGlt'
    'ZQpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKZnJvbSB0eXBpbmcgaW1wb3J0IE9wdGlvbmFsCgpm'
    'cm9tIHN0dWRpby5sbG0gaW1wb3J0IGNoYXQKCl9IRVJFICAgICAgICA9IFBhdGgoX19maWxlX18p'
    'LnJlc29sdmUoKS5wYXJlbnQKQTA5X0RJUiAgICAgID0gX0hFUkUgLyAiQTA5IgpQUk9NUFRfUEFU'
    'SCAgPSBBMDlfRElSIC8gImZvcmdlIiAvICJwcm9tcHQubWQiCkROQV9QQVRIICAgICA9IEEwOV9E'
    'SVIgLyAiZG5hLmpzb24iClNUQVRFX0RJUiAgICA9IF9IRVJFIC8gInN0YXRlIgpTVEFUU19QQVRI'
    'ICAgPSBTVEFURV9ESVIgLyAiZXhlY3V0b3Jfc3RhdHMuanNvbiIKTE9HX1BBVEggICAgID0gU1RB'
    'VEVfRElSIC8gImV4ZWN1dG9yX2xvZy5qc29ubCIgICAjINC70LXRgtC+0L/QuNGB0YwgKNCa0J7Q'
    'n9CY0KLQodCvKQoKIyDQnNCw0LPQuNGPIOKAlCDQv9Cw0YHQv9C+0YDRgtCwINGC0YDQtdC50LTQ'
    'tdGA0L7QsiAo0LjQtyDQv9GA0L7QvNGC0LAgQTA5LCDQutC+0L/QuNGA0YPQtdGC0YHRjyDRgtC+'
    '0YfQvdC+KQpNQUdJQyA9IHsiYnJ1dCI6IDEwMDAwMSwgImF2YW4iOiAxMDAwMDIsICJjb25zIjog'
    'MTAwMDAzfQpUUkFERVJfTkFNRSA9IHsiYnJ1dCI6ICJCUlVUIiwgImF2YW4iOiAiQVZBTlRVUklT'
    'VCIsICJjb25zIjogIktPTlNFUlZBVE9SIn0KCgojIOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAojINCi0JDQkdCb0J46INGB'
    '0L3QuNC80L7QuiDQstC10YDQtNC40LrRgtC+0LIg0YLRgNC+0LjRhSDRgtGA0LXQudC00LXRgNC+'
    '0LIg0LjQtyDRiNC40L3RiwojIOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAoKZGVmIF9yZWFkX3RyYWRlcnMoKSAtPiBkaWN0'
    'OgogICAgIiIi0JLQtdGA0LTQuNC60YLRiyDRgtGA0L7QuNGFINC40Lcg0L7QsdGJ0LXQuSDRiNC4'
    '0L3RiyAodHJhZGluZ19zdGF0ZSkuINCk0LDQutGCLCDQvdC1INGB0LvQvtCy0LAgTExNLiIiIgog'
    'ICAgZnJvbSBzdHVkaW8ubW9kdWxlcy50cmFkaW5nLmhvb2tzIGltcG9ydCBsb2FkX3RyYWRpbmdf'
    'c3RhdGUKICAgIHQgPSBsb2FkX3RyYWRpbmdfc3RhdGUoKQogICAgcmV0dXJuIHsKICAgICAgICAi'
    'YnJ1dCI6IHQuZ2V0KCJicnV0Iiwge30pLAogICAgICAgICJhdmFuIjogdC5nZXQoImF2YW4iLCB7'
    'fSksCiAgICAgICAgImNvbnMiOiB0LmdldCgiY29ucyIsIHt9KSwKICAgIH0KCgojIOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kAojINCg0KPQmtCQINCe0KLQmtCg0KvQktCQ0K7QqdCQ0K8gKNCa0J7QlCkg4oCUINC/0L7Qt9C4'
    '0YbQuNC4INC40Lcg0KLQkNCR0JvQniwg0L3QtSDQuNC3INGB0LvQvtCyIExMTQojIOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kAoKZGVmIF9vcGVuX3Bvc2l0aW9uc19mcm9tX3RhYmxlKHRyYWRlcnM6IGRpY3QsIG1hcmtldDog'
    'ZGljdCkgLT4gbGlzdDoKICAgICIiIgogICAg0JTQu9GPINC60LDQttC00L7Qs9C+IEFQUFJPVkVE'
    'LdGC0YDQtdC50LTQtdGA0LAg0LrQu9Cw0LTRkdGCINC/0L7Qt9C40YbQuNGOINCyIHRyYWRpbmdf'
    'c3RhdGVbInBvc2l0aW9ucyJdCiAgICDQn9CeINCk0JDQmtCi0KMg0KLQkNCR0JvQni4g0JLQvtC3'
    '0LLRgNCw0YnQsNC10YIg0YHQv9C40YHQvtC6INC+0YLQutGA0YvRgtGL0YUg0LIg0Y3RgtC+0YIg'
    '0YXQvtC0ICjQtNC70Y8g0LvQtdGC0L7Qv9C40YHQuCkuCgogICAg0JfQsNGJ0LjRgtCwINGH0LjR'
    'gdC10Ls6IGRpcmVjdGlvbi9lbnRyeS9zdG9wL2xvdCDQsdC10YDRkdC8INC40Lcg0YLQsNCx0LvQ'
    'viDRgtGA0LXQudC00LXRgNCwIOKAlAogICAg0Y3RgtC+INC10LPQviDQv9C+0LTQv9C40YHRjCwg'
    '0L3QtSDQv9C10YDQtdGB0LrQsNC3IExMTS4g0JTQuNGB0YbQuNC/0LvQuNC90LA6INC90LUg0L7R'
    'gtC60YDRi9Cy0LDQtdC8INC00YPQsdC70YwKICAgINGC0L7Qs9C+INC20LUgbWFnaWMsINC10YHQ'
    'u9C4INC+0L0g0YPQttC1INCy0LjRgdC40YIg0L7RgtC60YDRi9GC0YvQvC4KICAgICIiIgogICAg'
    'ZnJvbSBzdHVkaW8ubW9kdWxlcy50cmFkaW5nLmhvb2tzIGltcG9ydCBsb2FkX3RyYWRpbmdfc3Rh'
    'dGUsIHNhdmVfdHJhZGluZ19zdGF0ZQogICAgdHN0YXRlID0gbG9hZF90cmFkaW5nX3N0YXRlKCkK'
    'ICAgIHRzdGF0ZS5zZXRkZWZhdWx0KCJwb3NpdGlvbnMiLCBbXSkKICAgIG9wZW5fbWFnaWNzID0g'
    'e3AuZ2V0KCJtYWdpYyIpIGZvciBwIGluIHRzdGF0ZVsicG9zaXRpb25zIl0KICAgICAgICAgICAg'
    'ICAgICAgIGlmIHAuZ2V0KCJzdGF0dXMiKSA9PSAiT1BFTiJ9CgogICAgYmFyX3RpbWUgPSBtYXJr'
    'ZXQuZ2V0KCJiYXJfdGltZSIsICIiKQogICAgb3BlbmVkID0gW10KICAgIGZvciBrZXkgaW4gKCJi'
    'cnV0IiwgImF2YW4iLCAiY29ucyIpOgogICAgICAgIHYgPSB0cmFkZXJzLmdldChrZXksIHt9KQog'
    'ICAgICAgIGlmIHYuZ2V0KCJ2ZXJkaWN0IikgIT0gIkFQUFJPVkVEIjoKICAgICAgICAgICAgY29u'
    'dGludWUKICAgICAgICBtYWdpYyA9IE1BR0lDW2tleV0KICAgICAgICBpZiBtYWdpYyBpbiBvcGVu'
    'X21hZ2ljczoKICAgICAgICAgICAgIyDQtNC40YHRhtC40L/Qu9C40L3QsDog0L/QvtC30LjRhtC4'
    '0Y8g0Y3RgtC+0LPQviDRgtGA0LXQudC00LXRgNCwINGD0LbQtSDQttC40LLRkdGCIOKAlCDQvdC1'
    'INC00YPQsdC70LjRgNGD0LXQvAogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGRpcmVjdGlv'
    'biA9IHYuZ2V0KCJkaXJlY3Rpb24iKQogICAgICAgIGVudHJ5ICAgICA9IHYuZ2V0KCJlbnRyeSIp'
    'CiAgICAgICAgc3RvcCAgICAgID0gdi5nZXQoInN0b3AiKQogICAgICAgIGlmIGRpcmVjdGlvbiBu'
    'b3QgaW4gKCJMT05HIiwgIlNIT1JUIikgb3IgZW50cnkgaXMgTm9uZSBvciBzdG9wIGlzIE5vbmU6'
    'CiAgICAgICAgICAgICMg0LHQuNGC0YvQuSDQstC10YDQtNC40LrRgiDigJQg0L3QtSDQvtGC0LrR'
    'gNGL0LLQsNC10LwgKNGB0LDQvdC40YLQsNGAINGC0YDQtdC50LTQtdGA0LAg0LTQvtC70LbQtdC9'
    'INCx0YvQuwogICAgICAgICAgICAjINC/0L7Qs9Cw0YHQuNGC0YwsINC90L4g0LzRiyDQvdC1INC0'
    '0L7QstC10YDRj9C10Lwg0YHQu9C10L/QvikKICAgICAgICAgICAgY29udGludWUKICAgICAgICBw'
    'b3MgPSB7CiAgICAgICAgICAgICJ0cmFkZXIiOiAgICBUUkFERVJfTkFNRVtrZXldLAogICAgICAg'
    'ICAgICAibWFnaWMiOiAgICAgbWFnaWMsCiAgICAgICAgICAgICJkaXJlY3Rpb24iOiBkaXJlY3Rp'
    'b24sICAgICAgICAjIOKGkCDRhNC40LrRgSBkaXJlY3Rpb24g0YPRh9GC0ZHQvQogICAgICAgICAg'
    'ICAiZW50cnkiOiAgICAgZW50cnksCiAgICAgICAgICAgICJzdG9wIjogICAgICBzdG9wLAogICAg'
    'ICAgICAgICAidHAiOiAgICAgICAgTm9uZSwgICAgICAgICAgICAgIyDRgtC10LnQutCwINC90LXR'
    'giAowqc5KQogICAgICAgICAgICAibG90IjogICAgICAgdi5nZXQoImxvdCIpLAogICAgICAgICAg'
    'ICAic3RhdHVzIjogICAgIk9QRU4iLAogICAgICAgICAgICAibW9kZSI6ICAgICAgIlBBUEVSIiwK'
    'ICAgICAgICAgICAgIm9wZW5lZF9hdCI6IGJhcl90aW1lLAogICAgICAgICAgICAicG5sIjogICAg'
    'ICAgTm9uZSwKICAgICAgICB9CiAgICAgICAgdHN0YXRlWyJwb3NpdGlvbnMiXS5hcHBlbmQocG9z'
    'KQogICAgICAgIG9wZW5lZC5hcHBlbmQocG9zKQoKICAgIGlmIG9wZW5lZDoKICAgICAgICBzYXZl'
    'X3RyYWRpbmdfc3RhdGUodHN0YXRlKQogICAgcmV0dXJuIG9wZW5lZAoKCiMg4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQCiMg'
    '0JvQldCi0J7Qn9CY0KHQrCAo0JrQntCf0JjQotCh0K8sIGFwcGVuZCkg4oCUINGA0YPQutCwINC/'
    '0LjRiNGD0YnQsNGPIGhpc3RvcnlfZG5hCiMg4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQCgpkZWYgX2FwcGVuZF9sb2coc2ln'
    'bmFsOiBkaWN0LCBtYXJrZXQ6IGRpY3QsIG9wZW5lZDogbGlzdCk6CiAgICAiIiLQntGC0LrRgNGL'
    '0LLQsNC10YIg0LfQsNC/0LjRgdGMINCh0L7QstC10YLQsCDQsiDQu9C10YLQvtC/0LjRgdC4INCY'
    '0YHQv9C+0LvQvdC40YLQtdC70Y8gKNCa0J7Qn9CY0KLQodCvKS4iIiIKICAgIFNUQVRFX0RJUi5t'
    'a2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBldmVudCA9IHsKICAgICAgICAi'
    'dHMiOiAgICAgICAgICB0aW1lLnRpbWUoKSwKICAgICAgICAiYmFyX3RpbWUiOiAgICBtYXJrZXQu'
    'Z2V0KCJiYXJfdGltZSIpLAogICAgICAgICJzeW1ib2wiOiAgICAgIG1hcmtldC5nZXQoInN5bWJv'
    'bCIpLAogICAgICAgICJ0aW1lZnJhbWUiOiAgIG1hcmtldC5nZXQoInRpbWVmcmFtZSIpLAogICAg'
    'ICAgICJleGVjdXRpb25fbG9nIjogc2lnbmFsLmdldCgiZXhlY3V0aW9uX2xvZyIsIFtdKSwKICAg'
    'ICAgICAiZmluYWxfZG5hIjogICBzaWduYWwuZ2V0KCJmaW5hbF9kbmEiLCB7fSksCiAgICAgICAg'
    'Imhpc3RvcnlfZG5hIjogc2lnbmFsLmdldCgiaGlzdG9yeV9kbmEiLCAiIiksCiAgICAgICAgIm9w'
    'ZW5lZF9ub3ciOiAgW3sidHJhZGVyIjogcFsidHJhZGVyIl0sICJkaXJlY3Rpb24iOiBwWyJkaXJl'
    'Y3Rpb24iXSwKICAgICAgICAgICAgICAgICAgICAgICAgICJlbnRyeSI6IHBbImVudHJ5Il0sICJz'
    'dG9wIjogcFsic3RvcCJdfSBmb3IgcCBpbiBvcGVuZWRdLAogICAgfQogICAgd2l0aCBvcGVuKExP'
    'R19QQVRILCAiYSIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgZi53cml0ZShqc29u'
    'LmR1bXBzKGV2ZW50LCBlbnN1cmVfYXNjaWk9RmFsc2UpICsgIlxuIikKCgojIOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAoj'
    'INCh0KLQkNCi0JjQodCi0JjQmtCQICjQtNC70Y8g0LTQsNGI0LHQvtGA0LTQsCkKIyDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZAKCmRlZiBfbG9hZF9zdGF0cygpIC0+IGRpY3Q6CiAgICB0cnk6CiAgICAgICAgaWYgU1RBVFNf'
    'UEFUSC5leGlzdHMoKToKICAgICAgICAgICAgcmV0dXJuIGpzb24ubG9hZHMoU1RBVFNfUEFUSC5y'
    'ZWFkX3RleHQoZW5jb2Rpbmc9InV0Zi04IikpCiAgICBleGNlcHQgKGpzb24uSlNPTkRlY29kZUVy'
    'cm9yLCBPU0Vycm9yKToKICAgICAgICBwYXNzCiAgICByZXR1cm4geyJydW5zIjogMCwgIm9yZGVy'
    'c19zZW50IjogMCwgIm9yZGVyc19za2lwIjogMH0KCgpkZWYgX3VwZGF0ZV9zdGF0cyhvcGVuZWQ6'
    'IGxpc3QsIHRyYWRlcnM6IGRpY3QpIC0+IGRpY3Q6CiAgICBTVEFURV9ESVIubWtkaXIocGFyZW50'
    'cz1UcnVlLCBleGlzdF9vaz1UcnVlKQogICAgc3RhdHMgPSBfbG9hZF9zdGF0cygpCiAgICBzdGF0'
    'c1sicnVucyJdID0gc3RhdHMuZ2V0KCJydW5zIiwgMCkgKyAxCiAgICBhcHByb3ZlZCA9IHN1bSgx'
    'IGZvciBrIGluICgiYnJ1dCIsICJhdmFuIiwgImNvbnMiKQogICAgICAgICAgICAgICAgICAgaWYg'
    'dHJhZGVycy5nZXQoaywge30pLmdldCgidmVyZGljdCIpID09ICJBUFBST1ZFRCIpCiAgICBzdGF0'
    'c1sib3JkZXJzX3NlbnQiXSA9IHN0YXRzLmdldCgib3JkZXJzX3NlbnQiLCAwKSArIGxlbihvcGVu'
    'ZWQpCiAgICBzdGF0c1sib3JkZXJzX3NraXAiXSA9IHN0YXRzLmdldCgib3JkZXJzX3NraXAiLCAw'
    'KSArICgzIC0gYXBwcm92ZWQpCiAgICBTVEFUU19QQVRILndyaXRlX3RleHQoCiAgICAgICAganNv'
    'bi5kdW1wcyhzdGF0cywgZW5zdXJlX2FzY2lpPUZhbHNlLCBpbmRlbnQ9MiksIGVuY29kaW5nPSJ1'
    'dGYtOCIpCiAgICByZXR1cm4gc3RhdHMKCgojIOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAojINCf0JDQoNCh0JjQndCTINCU'
    '0JLQo9Cl0KHQm9Ce0JnQndCe0JPQniDQntCi0JLQldCi0JAge25hcnJhdGl2ZSwgc2lnbmFsfQoj'
    'IOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkAoKZGVmIF9wYXJzZV9leGVjdXRvcihyZXNwb25zZTogc3RyKSAtPiB0dXBsZVtz'
    'dHIsIGRpY3RdOgogICAgY2xlYW5lZCA9IHJlLnN1YihyImBgYCg/Ompzb24pPyIsICIiLCByZXNw'
    'b25zZSkuc3RyaXAoKQogICAgc3RhcnQgPSBjbGVhbmVkLmZpbmQoInsiKQogICAgaWYgc3RhcnQg'
    'IT0gLTE6CiAgICAgICAgZGVwdGggPSAwCiAgICAgICAgZm9yIGkgaW4gcmFuZ2Uoc3RhcnQsIGxl'
    'bihjbGVhbmVkKSk6CiAgICAgICAgICAgIGlmIGNsZWFuZWRbaV0gPT0gInsiOgogICAgICAgICAg'
    'ICAgICAgZGVwdGggKz0gMQogICAgICAgICAgICBlbGlmIGNsZWFuZWRbaV0gPT0gIn0iOgogICAg'
    'ICAgICAgICAgICAgZGVwdGggLT0gMQogICAgICAgICAgICAgICAgaWYgZGVwdGggPT0gMDoKICAg'
    'ICAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgICAgIG9iaiA9IGpzb24u'
    'bG9hZHMoY2xlYW5lZFtzdGFydDppICsgMV0pCiAgICAgICAgICAgICAgICAgICAgICAgIHJldHVy'
    'biAob2JqLmdldCgibmFycmF0aXZlIiwgIiIpLAogICAgICAgICAgICAgICAgICAgICAgICAgICAg'
    'ICAgIG9iai5nZXQoInNpZ25hbCIsIHt9KSBvciB7fSkKICAgICAgICAgICAgICAgICAgICBleGNl'
    'cHQganNvbi5KU09ORGVjb2RlRXJyb3I6CiAgICAgICAgICAgICAgICAgICAgICAgIGJyZWFrCiAg'
    'ICByZXR1cm4gcmVzcG9uc2Uuc3RyaXAoKSwge30KCgpkZWYgX2J1aWxkX2V4ZWN1dGlvbl9sb2df'
    'ZmFjdHModHJhZGVyczogZGljdCkgLT4gbGlzdDoKICAgICIiIgogICAg0JrQntCUINGB0L7QsdC4'
    '0YDQsNC10YIg0L/RgNCw0LLQtNC40LLRi9C5IGV4ZWN1dGlvbl9sb2cg0LjQtyDQotCQ0JHQm9Ce'
    'IOKAlCDRjdGC0LDQu9C+0L0sINC/0L4g0LrQvtGC0L7RgNC+0LzRgwogICAg0YHQstC10YDRj9C1'
    '0YLRgdGPINC70LXRgtC+0L/QuNGB0YwgTExNICjQt9Cw0YnQuNGC0LAg0YfQuNGB0LXQuykuINCt'
    '0YLQviDRhNCw0LrRgiwg0L3QtSDQv9C10YDQtdGB0LrQsNC3LgogICAgIiIiCiAgICBsb2cgPSBb'
    'XQogICAgZm9yIGtleSBpbiAoImJydXQiLCAiYXZhbiIsICJjb25zIik6CiAgICAgICAgdiA9IHRy'
    'YWRlcnMuZ2V0KGtleSwge30pCiAgICAgICAgYXBwcm92ZWQgPSB2LmdldCgidmVyZGljdCIpID09'
    'ICJBUFBST1ZFRCIKICAgICAgICBsb2cuYXBwZW5kKHsKICAgICAgICAgICAgInRyYWRlciI6ICBU'
    'UkFERVJfTkFNRVtrZXldLAogICAgICAgICAgICAibWFnaWMiOiAgIE1BR0lDW2tleV0sCiAgICAg'
    'ICAgICAgICJ2ZXJkaWN0IjogIkFQUFJPVkVEIiBpZiBhcHByb3ZlZCBlbHNlICJSRUpFQ1RFRCIs'
    'CiAgICAgICAgICAgICJkaXJlY3Rpb24iOiB2LmdldCgiZGlyZWN0aW9uIikgaWYgYXBwcm92ZWQg'
    'ZWxzZSBOb25lLAogICAgICAgICAgICAiZW50cnkiOiAgIHYuZ2V0KCJlbnRyeSIpIGlmIGFwcHJv'
    'dmVkIGVsc2UgTm9uZSwKICAgICAgICAgICAgInN0b3AiOiAgICB2LmdldCgic3RvcCIpIGlmIGFw'
    'cHJvdmVkIGVsc2UgTm9uZSwKICAgICAgICAgICAgImxvdCI6ICAgICB2LmdldCgibG90IikgaWYg'
    'YXBwcm92ZWQgZWxzZSBOb25lLAogICAgICAgICAgICAic3RhdHVzIjogICJQQVBFUiIgaWYgYXBw'
    'cm92ZWQgZWxzZSAiU0tJUFBFRCIsCiAgICAgICAgICAgICJwbmwiOiAgICAgTm9uZSwKICAgICAg'
    'ICB9KQogICAgcmV0dXJuIGxvZwoKCmRlZiBfc2FuaXRpemUoc2lnbmFsOiBkaWN0LCB0cmFkZXJz'
    'OiBkaWN0KSAtPiBkaWN0OgogICAgIiIiCiAgICDQl9CQ0KnQmNCi0JAg0KfQmNCh0JXQmzogZXhl'
    'Y3V0aW9uX2xvZyDQsiBzaWduYWwg0L/QtdGA0LXRgtC40YDQsNC10Lwg0YTQsNC60YLQsNC80Lgg'
    '0LjQtyDRgtCw0LHQu9C+IOKAlAogICAg0JjRgdC/0L7Qu9C90LjRgtC10LvRjCDCq9C40YHQv9C+'
    '0LvQvdGP0LXRgiDQsdGD0LrQstCw0LvRjNC90L7Cuywg0LXQs9C+INGB0LzQtdGA0YLQvdGL0Lkg'
    '0LPRgNC10YUg0LLRgNCw0YLRjCDQsiDRh9C40YHQu9Cw0YUuCiAgICDQmtC+0LQt0YTQsNC60YIg'
    '0LLRgdC10LPQtNCwINC/0L7QsdC10LbQtNCw0LXRgiDRgdC70L7QstCwIExMTS4gaGlzdG9yeV9k'
    'bmEvdGFza19zY29yZSDigJQKICAgINC+0YHRgtCw0LLQu9GP0LXQvCDQtdCz0L4gKNGN0YLQviDQ'
    'tdCz0L4g0YHRg9C20LTQtdC90LjQtSDQviDQtNC40YHRhtC40L/Qu9C40L3QtSwg0L3QtSDRh9C4'
    '0YHQu9CwKS4KICAgICIiIgogICAgZmFjdHMgPSBfYnVpbGRfZXhlY3V0aW9uX2xvZ19mYWN0cyh0'
    'cmFkZXJzKQogICAgc2lnbmFsWyJleGVjdXRpb25fbG9nIl0gPSBmYWN0cwogICAgc2VudCA9IHN1'
    'bSgxIGZvciBvIGluIGZhY3RzIGlmIG9bInZlcmRpY3QiXSA9PSAiQVBQUk9WRUQiKQogICAgZmQg'
    'PSBzaWduYWwuZ2V0KCJmaW5hbF9kbmEiLCB7fSkgb3Ige30KICAgIGZkWyJvcmRlcnNfc2VudCJd'
    'ID0gc2VudAogICAgZmRbIm9yZGVyc19za2lwIl0gPSAzIC0gc2VudAogICAgc2lnbmFsWyJmaW5h'
    'bF9kbmEiXSA9IGZkCiAgICByZXR1cm4gc2lnbmFsCgoKIyDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZAKIyDQp9CQ0KIg0KEg'
    '0JjQodCf0J7Qm9Cd0JjQotCV0JvQldCcICjQutC70LjQuiDQv9GD0LfRi9GA0YzQutCwKQojIOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkAoKZGVmIGNoYXRfd2l0aF9leGVjdXRvcihxdWVzdGlvbjogc3RyLCBsYXN0X3J1bjog'
    'T3B0aW9uYWxbZGljdF0gPSBOb25lLAogICAgICAgICAgICAgICAgICAgICAgIGRpYWxvZzogT3B0'
    'aW9uYWxbbGlzdF0gPSBOb25lKSAtPiBzdHI6CiAgICBwcm9tcHQgPSBQUk9NUFRfUEFUSC5yZWFk'
    'X3RleHQoZW5jb2Rpbmc9InV0Zi04IikgaWYgUFJPTVBUX1BBVEguZXhpc3RzKCkgZWxzZSAiIgoK'
    'ICAgIGlmIGxhc3RfcnVuOgogICAgICAgIHNpZyA9IGxhc3RfcnVuLmdldCgic2lnbmFsIiwge30p'
    'CiAgICAgICAgbWsgID0gbGFzdF9ydW4uZ2V0KCJtYXJrZXQiLCB7fSkKICAgICAgICBoaXN0ID0g'
    'c2lnLmdldCgiaGlzdG9yeV9kbmEiLCAiIikKICAgICAgICBmZCAgID0gc2lnLmdldCgiZmluYWxf'
    'ZG5hIiwge30pCiAgICAgICAgd29ya19jdHggPSAoCiAgICAgICAgICAgICJcblxuPT09INCi0JLQ'
    'ntCZINCf0J7QodCb0JXQlNCd0JjQmSDQodCe0JLQldCiICjRgNCw0LHQvtGH0LDRjyDQv9Cw0LzR'
    'j9GC0YwpID09PVxuIgogICAgICAgICAgICBmItCY0L3RgdGC0YDRg9C80LXQvdGCOiB7bWsuZ2V0'
    'KCdzeW1ib2wnLCc/Jyl9IHttay5nZXQoJ3RpbWVmcmFtZScsJz8nKX0gIgogICAgICAgICAgICBm'
    'IsK3INCx0LDRgCB7bWsuZ2V0KCdiYXJfdGltZScsJz8nKX1cbiIKICAgICAgICAgICAgZiLQntGA'
    '0LTQtdGA0L7Qsjoge2ZkLmdldCgnb3JkZXJzX3NlbnQnLCfigJQnKX0g0LjQtyAzIMK3ICIKICAg'
    'ICAgICAgICAgZiJ0YXNrX3Njb3JlOiB7ZmQuZ2V0KCd0YXNrX3Njb3JlJywn4oCUJyl9XG4iCiAg'
    'ICAgICAgICAgIGYi0JvQtdGC0L7Qv9C40YHRjDoge2hpc3R9XG4iCiAgICAgICAgICAgICI9PT0g'
    '0JrQntCd0JXQpiA9PT1cblxuIgogICAgICAgICAgICAi0KjQtdGEINGB0L/RgNCw0YjQuNCy0LDQ'
    'tdGCINC/0YDQviDQrdCi0J7QoiDQodC+0LLQtdGCLiDQntGC0LLQtdGH0LDQuSDQutCw0Log0JjR'
    'gdC/0L7Qu9C90LjRgtC10LvRjCDigJQgIgogICAgICAgICAgICAi0L3QtdC50YLRgNCw0LvRjNC9'
    '0L4sINGC0L7Rh9C90L4sINGE0LDQutGC0LDQvNC4LiDQltC40LLRi9C8INCz0L7Qu9C+0YHQvtC8'
    'LCDQkdCV0JcgSlNPTi4iCiAgICAgICAgKQogICAgZWxzZToKICAgICAgICB3b3JrX2N0eCA9ICgK'
    'ICAgICAgICAgICAgIlxuXG49PT0g0KDQkNCR0J7Qp9CY0Jkg0KDQldCW0JjQnCA9PT1cbiIKICAg'
    'ICAgICAgICAgItCi0Ysg0LXRidGRINC90LUg0LjRgdC/0L7Qu9C90Y/QuyDQsiDRjdGC0L7QuSDR'
    'gdC10YHRgdC40LguINCV0YHQu9C4INCo0LXRhCDRgdC/0YDQsNGI0LjQstCw0LXRgiDQv9GA0L4g'
    'IgogICAgICAgICAgICAi0L7RgNC00LXRgNCwIOKAlCDRgdC60LDQttC4LCDRh9GC0L4g0L3Rg9C2'
    '0LXQvSDQv9GA0L7Qs9C+0L0g0KDQq9Cd0J7Qmi4g0JbQuNCy0YvQvCDQs9C+0LvQvtGB0L7QvCwg'
    '0LHQtdC3IEpTT04uIgogICAgICAgICkKCiAgICBzeXN0ZW0gPSBwcm9tcHQgKyB3b3JrX2N0eAog'
    'ICAgdHJ5OgogICAgICAgIGZyb20gc3R1ZGlvLmdyb25kaGVpbV9tZW1vcnkgaW1wb3J0IGZvcm1h'
    'dF9zb3VsX2Zvcl9hZ2VudAogICAgICAgIHNvdWwgPSBmb3JtYXRfc291bF9mb3JfYWdlbnQoIkEw'
    'OV9JU1BPTE5JVEVMIiwgZGVwdD0idHJhZGluZyIpCiAgICAgICAgaWYgc291bDoKICAgICAgICAg'
    'ICAgc3lzdGVtID0gcHJvbXB0ICsgIlxuXG49PT0g0KLQktCe0IEg0KHQntCh0KLQntCv0J3QmNCV'
    'ICjQtNGD0YjQsCkgPT09XG4iICsgc291bCArICJcblxuIiArIHdvcmtfY3R4CiAgICBleGNlcHQg'
    'RXhjZXB0aW9uOgogICAgICAgIHBhc3MKCiAgICBoaXN0b3J5ID0gW10KICAgIGlmIGRpYWxvZzoK'
    'ICAgICAgICBmb3IgbSBpbiBkaWFsb2dbOi0xXToKICAgICAgICAgICAgciA9IG0uZ2V0KCJyb2xl'
    'Iik7IGMgPSBtLmdldCgiY29udGVudCIsICIiKQogICAgICAgICAgICBpZiByIGluICgidXNlciIs'
    'ICJhc3Npc3RhbnQiKSBhbmQgYzoKICAgICAgICAgICAgICAgIGhpc3RvcnkuYXBwZW5kKHsicm9s'
    'ZSI6IHIsICJjb250ZW50IjogY30pCgogICAgdHJ5OgogICAgICAgIHJldHVybiBjaGF0KHN5c3Rl'
    'bT1zeXN0ZW0sIHVzZXI9cXVlc3Rpb24sIGhpc3Rvcnk9aGlzdG9yeSwKICAgICAgICAgICAgICAg'
    'ICAgICBhZ2VudF9pZD0iQTA5X0lTUE9MTklURUwiLCBzbG90X2lkPSJ0cmFkaW5nIikKICAgIGV4'
    'Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICByZXR1cm4gZiLimqDvuI8g0JjRgdC/0L7Qu9C9'
    '0LjRgtC10LvRjCDQvdC1INGB0LzQvtCzINC+0YLQstC10YLQuNGC0Yw6IHtlfSIKCgojIOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkAojINCT0JvQkNCS0J3QkNCvINCk0KPQndCa0KbQmNCvIOKAlCDQmNGB0L/QvtC70L3QuNGC'
    '0LXQu9GMINC30LDQvNGL0LrQsNC10YIg0L/QtdGC0LvRjgojIOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAoKZGVmIHJ1bl9l'
    'eGVjdXRvcihzeW1ib2w6IHN0ciA9ICJYQVVVU0QiLCB0aW1lZnJhbWU6IHN0ciA9ICJINCIpIC0+'
    'IGRpY3Q6CiAgICAiIiIKICAgINCe0LTQuNC9INGF0L7QtCDQmNGB0L/QvtC70L3QuNGC0LXQu9GP'
    'LiDQp9C40YLQsNC10YIg0YLQsNCx0LvQviDRgtGA0L7QuNGFIOKGkiDQmtCe0JQg0L7RgtC60YDR'
    'i9Cy0LDQtdGCINC/0L7Qt9C40YbQuNC4INC/0L4KICAgINGE0LDQutGC0YMg4oaSIExMTSDQv9C4'
    '0YjQtdGCINC70LXRgtC+0L/QuNGB0YwuINCd0LUg0YHQvNC+0YLRgNC40YIg0YDRi9C90L7QuiDR'
    'gdCy0L7QuNC8INC+0YDQs9Cw0L3QvtC8LCDQvdC1INGA0LXRiNCw0LXRgi4KCiAgICDQktC+0LfQ'
    'stGA0LDRidCw0LXRgiAo0LrQsNC6INC00LLQuNC20LrQuCk6IHtvaywgZXJyb3IsIG5hcnJhdGl2'
    'ZSwgc2lnbmFsLCBzdGF0cywgbWFya2V0fS4KICAgICIiIgogICAgIyDilIDilIAgMS4g0KLQsNCx'
    '0LvQviDRgtGA0L7QuNGFICsg0LrQvtC90YLQtdC60YHRgiDQsdCw0YDQsCDilIDilIDilIDilIDi'
    'lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAK'
    'ICAgIHRyYWRlcnMgPSBfcmVhZF90cmFkZXJzKCkKCiAgICAjINC90LDRgdC70LXQtNGD0LXQvCDR'
    'jdGC0LDQtiDQmNGB0LrRgNGLICjQutCw0Log0YLRgNC10LnQtNC10YDRiyksINC/0L7QtNC90LjQ'
    'vNCw0LXQvCDQutC+0L3RgtGD0YAg0YDQsNC00LgKICAgICMg0YfQtdGB0YLQvdC+0LPQviBiYXJf'
    'dGltZSDigJQg0JjRgdC/0L7Qu9C90LjRgtC10LvRjCDQv9C40YjQtdGCINC70LXRgtC+0L/QuNGB'
    '0YwsINC10LzRgyDQvdGD0LbQvdCwINC/0YDQsNCy0LTQsAogICAgIyDQviDQsdCw0YDQtSwg0LAg'
    '0L3QtSDQstGL0LTRg9C80LDQvdC90LDRjyDQv9GD0YHRgtC+0YLQsC4KICAgIGZyb20gc3R1ZGlv'
    'Lm1vZHVsZXMudHJhZGluZy5ob29rcyBpbXBvcnQgbG9hZF90cmFkaW5nX3N0YXRlCiAgICB0c3Rh'
    'dGUgPSBsb2FkX3RyYWRpbmdfc3RhdGUoKQogICAgaXNrcmFfdGYgPSB0c3RhdGUuZ2V0KCJpc2ty'
    'YSIsIHt9KS5nZXQoImZvdW5kX3RpbWVmcmFtZSIpIG9yIHRpbWVmcmFtZQoKICAgIG1hcmtldCA9'
    'IHsic3ltYm9sIjogc3ltYm9sLCAidGltZWZyYW1lIjogaXNrcmFfdGYsICJiYXJfdGltZSI6ICIi'
    'fQogICAgdHJ5OgogICAgICAgIGZyb20gc3R1ZGlvLm1vZHVsZXMudHJhZGluZy5tdDVfZmVlZCBp'
    'bXBvcnQgX3Rlcm1pbmFsLCBfZmV0Y2gKICAgICAgICBmcm9tIHN0dWRpby5tb2R1bGVzLnRyYWRp'
    'bmcud2lsbGlhbXNfY29yZSBpbXBvcnQgYnVpbGRfbWFya2V0X2RhdGEKICAgICAgICBtdDUgPSBf'
    'dGVybWluYWwoKQogICAgICAgIGlmIG10NSBpcyBub3QgTm9uZToKICAgICAgICAgICAgYmFycywg'
    'cG9pbnQgPSBfZmV0Y2gobXQ1LCBzeW1ib2wsIGlza3JhX3RmLCAzMDApCiAgICAgICAgICAgIGlm'
    'IGJhcnMgYW5kIHBvaW50IGlzIG5vdCBOb25lOgogICAgICAgICAgICAgICAgbWQgPSBidWlsZF9t'
    'YXJrZXRfZGF0YShiYXJzLCBzeW1ib2w9c3ltYm9sLAogICAgICAgICAgICAgICAgICAgICAgICAg'
    'ICAgICAgICAgICAgICB0aW1lZnJhbWU9aXNrcmFfdGYsIHBvaW50PXBvaW50KQogICAgICAgICAg'
    'ICAgICAgaWYgbWQ6CiAgICAgICAgICAgICAgICAgICAgbWFya2V0WyJiYXJfdGltZSJdICA9IG1k'
    'LmdldCgiYmFyX3RpbWUiLCAiIikKICAgICAgICAgICAgICAgICAgICBtYXJrZXRbInRpbWVmcmFt'
    'ZSJdID0gaXNrcmFfdGYKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICBwcmludChm'
    'IltFWEVDVVRPUl0g4pqg77iPICBiYXJfdGltZSDQvdC1INC/0L7QtNC90Y/Qu9GB0Y8gKHtlfSkg'
    '4oCUINC70LXRgtC+0L/QuNGB0Ywg0LHQtdC3INGC0L7Rh9C90L7Qs9C+INCx0LDRgNCwIikKCiAg'
    'ICAjIOKUgOKUgCAyLiDQoNCj0JrQkCDQntCi0JrQoNCr0JLQkNCu0KnQkNCvICjQmtCe0JQpIOKA'
    'lCDQv9C+0LfQuNGG0LjQuCDQv9C+INGE0LDQutGC0YMg0YLQsNCx0LvQviDilIDilIDilIDilIAK'
    'ICAgIG9wZW5lZCA9IF9vcGVuX3Bvc2l0aW9uc19mcm9tX3RhYmxlKHRyYWRlcnMsIG1hcmtldCkK'
    'CiAgICAjIOKUgOKUgCAzLiDQlNGD0YjQsCArINCU0J3QmiArINC/0YDQvtC80YIg4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiAgICBzb3VsID0gIiIKICAgIHRyeToKICAg'
    'ICAgICBmcm9tIHN0dWRpby5ncm9uZGhlaW1fbWVtb3J5IGltcG9ydCBmb3JtYXRfc291bF9mb3Jf'
    'YWdlbnQKICAgICAgICBzb3VsID0gZm9ybWF0X3NvdWxfZm9yX2FnZW50KCJBMDlfSVNQT0xOSVRF'
    'TCIsIGRlcHQ9InRyYWRpbmciKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIHBy'
    'aW50KGYiW0VYRUNVVE9SXSDimqDvuI8gINCU0YPRiNCwINC90LUg0LfQsNCz0YDRg9C30LjQu9Cw'
    '0YHRjCAoe2V9KSDigJQg0YDQsNCx0L7RgtCw0Y4g0LHQtdC3INC90LXRkSIpCgogICAgZG5hX3Jh'
    'dyA9ICIiCiAgICB0cnk6CiAgICAgICAgaWYgRE5BX1BBVEguZXhpc3RzKCk6CiAgICAgICAgICAg'
    'IGRuYV9yYXcgPSBETkFfUEFUSC5yZWFkX3RleHQoZW5jb2Rpbmc9InV0Zi04IikKICAgIGV4Y2Vw'
    'dCBPU0Vycm9yOgogICAgICAgIHBhc3MKCiAgICBwcm9tcHQgPSBQUk9NUFRfUEFUSC5yZWFkX3Rl'
    'eHQoZW5jb2Rpbmc9InV0Zi04IikgaWYgUFJPTVBUX1BBVEguZXhpc3RzKCkgZWxzZSAiIgoKICAg'
    'ICMg4pSA4pSAIDQuINCg0JDQodCa0JvQkNCU0JrQkCDQtNC70Y8g0LvQtdGC0L7Qv9C40YHRhtCw'
    'IOKAlCDRgtCw0LHQu9C+ICsg0YfRgtC+INC60L7QtCDRg9C20LUg0L7RgtC60YDRi9C7IOKUgAog'
    'ICAgZmFjdHMgPSBfYnVpbGRfZXhlY3V0aW9uX2xvZ19mYWN0cyh0cmFkZXJzKQogICAgdGFibGVf'
    'Zm9yX2V4ZWMgPSB7CiAgICAgICAgInRyYWRlcnMiOiB7CiAgICAgICAgICAgICJicnV0Ijoge2s6'
    'IHRyYWRlcnNbImJydXQiXS5nZXQoaykgZm9yIGsgaW4KICAgICAgICAgICAgICAgICAgICAgKCJ2'
    'ZXJkaWN0IiwgInJlYXNvbiIsICJkaXJlY3Rpb24iLCAiZW50cnkiLCAic3RvcCIsICJsb3QiKX0s'
    'CiAgICAgICAgICAgICJhdmFuIjoge2s6IHRyYWRlcnNbImF2YW4iXS5nZXQoaykgZm9yIGsgaW4K'
    'ICAgICAgICAgICAgICAgICAgICAgKCJ2ZXJkaWN0IiwgInJlYXNvbiIsICJkaXJlY3Rpb24iLCAi'
    'ZW50cnkiLCAic3RvcCIsICJsb3QiKX0sCiAgICAgICAgICAgICJjb25zIjoge2s6IHRyYWRlcnNb'
    'ImNvbnMiXS5nZXQoaykgZm9yIGsgaW4KICAgICAgICAgICAgICAgICAgICAgKCJ2ZXJkaWN0Iiwg'
    'InJlYXNvbiIsICJkaXJlY3Rpb24iLCAiZW50cnkiLCAic3RvcCIsICJsb3QiKX0sCiAgICAgICAg'
    'fSwKICAgICAgICAibWFnaWMiOiAgICAgICAgTUFHSUMsCiAgICAgICAgImZhY3RzX2xvZyI6ICAg'
    'IGZhY3RzLCAgICAgICAgICAgICAjINGN0YLQsNC70L7QvSBleGVjdXRpb25fbG9nICjQutC+0LQg'
    '0L/QvtGB0YfQuNGC0LDQuykKICAgICAgICAib3BlbmVkX25vdyI6ICAgbGVuKG9wZW5lZCksCiAg'
    'ICAgICAgIm9wZW5fcG9zaXRpb25zIjogdHN0YXRlLmdldCgicG9zaXRpb25zIiwgW10pLAogICAg'
    'ICAgICJpc2tyYV90MSI6ICAgICB0c3RhdGUuZ2V0KCJpc2tyYSIsIHt9KS5nZXQoInQxX3N0YXR1'
    'cyIpLAogICAgICAgICJtYXJrZXQiOiAgICAgICBtYXJrZXQsCiAgICB9CgogICAgdXNlcl9tc2cg'
    'PSAoCiAgICAgICAgIj09PSDQotCQ0JHQm9CeINCh0J7QktCV0KLQkCAo0LLQtdGA0LTQuNC60YLR'
    'iyDRgtGA0L7QuNGFINGC0YDQtdC50LTQtdGA0L7QsiDigJQg0KTQkNCa0KIpID09PVxuIgogICAg'
    'ICAgIGYie2pzb24uZHVtcHModGFibGVfZm9yX2V4ZWMsIGVuc3VyZV9hc2NpaT1GYWxzZSwgaW5k'
    'ZW50PTIpfVxuXG4iCiAgICAgICAgItCi0Ysg4oCUINCY0YHQv9C+0LvQvdC40YLQtdC70YwuINCi'
    '0Ysg0J3QlSDRgdGD0LTQuNGI0Ywg0YDRi9C90L7QuiDQuCDQndCVINGB0YfQuNGC0LDQtdGI0Ywg'
    'UG5MICjRjdGC0L4g0LrQvtC0KS4gIgogICAgICAgICLQmtC+0LQg0YPQttC1INC+0YLQutGA0YvQ'
    'uyDQv9C+0LfQuNGG0LjQuCDQv9C+INGE0LDQutGC0YMg0YLQsNCx0LvQviAoUEFQRVIpLiDQotCy'
    '0L7RjyDRgNCw0LHQvtGC0LA6ICIKICAgICAgICAi0YHQvtCx0YDQsNGC0YwgZXhlY3V0aW9uX2xv'
    'ZyAo0LHQtdGA0Lgg0YfQuNGB0LvQsCDQotCe0KfQndCeINC40Lcg0YLQsNCx0LvQviDigJQgZmFj'
    'dHNfbG9nINGC0LXQsdC1ICIKICAgICAgICAi0Y3RgtCw0LvQvtC9LCDQvdC40LrQvtCz0LTQsCDQ'
    'vdC1INC/0YPRgtCw0LkgbWFnaWMpLCDQvdCw0L/QuNGB0LDRgtGMIGhpc3RvcnlfZG5hIOKAlCDQ'
    'ntCU0J3QoyDRgdGC0YDQvtC60YMgIgogICAgICAgICLQv9GA0LDQstC00Ysg0L7QsSDRjdGC0L7Q'
    'vCDQodC+0LLQtdGC0LUg0LHQtdC3INC40L3RgtC10YDQv9GA0LXRgtCw0YbQuNC5LCDQuCDQv9C+'
    '0YHRgtCw0LLQuNGC0YwgdGFza19zY29yZSDigJQgIgogICAgICAgICLRh9C10YHRgtC90YPRjiDQ'
    'vtGG0LXQvdC60YMg0JTQmNCh0KbQmNCf0JvQmNCd0Ksg0YbQtdGF0LAgKNC90LUg0L/RgNC40LHR'
    'i9C70Lg6INC/0L7RgtC+0LvQvtC6IDYuMDsg0LLRgdC1INGC0YDQvtC1ICIKICAgICAgICAiUkVK'
    'RUNURUQg0YEg0LLQvdGP0YLQvdGL0LzQuCDQv9GA0LjRh9C40L3QsNC80Lgg4oCUINGC0L7QttC1'
    'INGF0L7RgNC+0YjQsNGPINGA0LDQsdC+0YLQsCwg0YbQtdGFINGB0Y3QutC+0L3QvtC80LjQuyku'
    'ICIKICAgICAgICAi0JLRi9C00LDQuSDRgdGC0YDQvtCz0L4gSlNPTiB7bmFycmF0aXZlLCBzaWdu'
    'YWx9LiBzaWduYWw6IGV4ZWN1dGlvbl9sb2csICIKICAgICAgICAiZmluYWxfZG5hIChzeW1ib2ws'
    'IHRpbWVmcmFtZSwgYmFyX3RpbWUsIHQxX3N0YXR1cywgb3JkZXJzX3NlbnQsICIKICAgICAgICAi'
    'b3JkZXJzX3NraXAsIHRhc2tfc2NvcmUpLCBoaXN0b3J5X2RuYSwgZGVsaXZlcmFibGVzLiDQndC4'
    '0YfQtdCz0L4g0LLQvdC1IEpTT04uIgogICAgKQoKICAgIHN5c3RlbV9mdWxsID0gcHJvbXB0CiAg'
    'ICBpZiBkbmFfcmF3OgogICAgICAgIHN5c3RlbV9mdWxsICs9ICJcblxuPT09INCS0J7QoiDQotCr'
    'ICjRgtCy0L7RjyDQlNCd0Jog4oCUINGH0LjRgtCw0Lkg0LrQsNC6INGB0LXQsdGPKSA9PT1cbiIg'
    'KyBkbmFfcmF3CiAgICBpZiBzb3VsOgogICAgICAgIHN5c3RlbV9mdWxsICs9ICJcblxuPT09INCi'
    '0JLQntCBINCh0J7QodCi0J7Qr9Cd0JjQlSAo0LTRg9GI0LApID09PVxuIiArIHNvdWwKCiAgICB0'
    'cnk6CiAgICAgICAgcmVzcG9uc2UgPSBjaGF0KHN5c3RlbT1zeXN0ZW1fZnVsbCwgdXNlcj11c2Vy'
    'X21zZywKICAgICAgICAgICAgICAgICAgICAgICAgYWdlbnRfaWQ9IkEwOV9JU1BPTE5JVEVMIiwg'
    'c2xvdF9pZD0idHJhZGluZyIpCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgIyBM'
    'TE0g0YPQv9Cw0Lsg4oCUINC90L4g0L/QvtC30LjRhtC40Lgg0KPQltCVINC+0YLQutGA0YvRgtGL'
    'INC60L7QtNC+0LwgKNC/0LXRgtC70Y8g0YbQtdC70LApLiDQm9C10YLQvtC/0LjRgdGMCiAgICAg'
    'ICAgIyDRgdC+0LHQtdGA0ZHQvCDQuNC3INGE0LDQutGC0L7Qsiwg0LHQtdC3INCz0L7Qu9C+0YHQ'
    'sC4KICAgICAgICBmYWN0c19zaWcgPSB7ImV4ZWN1dGlvbl9sb2ciOiBmYWN0cywKICAgICAgICAg'
    'ICAgICAgICAgICAgImZpbmFsX2RuYSI6IHsic3ltYm9sIjogbWFya2V0WyJzeW1ib2wiXSwKICAg'
    'ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidGltZWZyYW1lIjogbWFya2V0WyJ0aW1l'
    'ZnJhbWUiXSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiYmFyX3RpbWUiOiBt'
    'YXJrZXRbImJhcl90aW1lIl0sCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInQx'
    'X3N0YXR1cyI6IHRzdGF0ZS5nZXQoImlza3JhIiwge30pLmdldCgidDFfc3RhdHVzIiksCiAgICAg'
    'ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIm9yZGVyc19zZW50IjogbGVuKG9wZW5lZCks'
    'CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIm9yZGVyc19za2lwIjogMyAtIGxl'
    'bihvcGVuZWQpLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0YXNrX3Njb3Jl'
    'IjogTm9uZX0sCiAgICAgICAgICAgICAgICAgICAgICJoaXN0b3J5X2RuYSI6ICIiLCAiZGVsaXZl'
    'cmFibGVzIjogW119CiAgICAgICAgX2FwcGVuZF9sb2coZmFjdHNfc2lnLCBtYXJrZXQsIG9wZW5l'
    'ZCkKICAgICAgICBzdGF0cyA9IF91cGRhdGVfc3RhdHMob3BlbmVkLCB0cmFkZXJzKQogICAgICAg'
    'IHJldHVybiB7Im9rIjogVHJ1ZSwgImVycm9yIjogZiLQu9C10YLQvtC/0LjRgdGMINCx0LXQtyDQ'
    's9C+0LvQvtGB0LAgKExMTToge2V9KSIsCiAgICAgICAgICAgICAgICAibmFycmF0aXZlIjogZiLQ'
    'ntGA0LTQtdGA0L7Qsjoge2xlbihvcGVuZWQpfSDQuNC3IDMuINCY0YHQv9C+0LvQvdC10L3Qvi4i'
    'LAogICAgICAgICAgICAgICAgInNpZ25hbCI6IGZhY3RzX3NpZywgInN0YXRzIjogc3RhdHMsICJt'
    'YXJrZXQiOiBtYXJrZXR9CgogICAgIyDilIDilIAgNS4g0J/QsNGA0YEgKyDQt9Cw0YnQuNGC0LAg'
    '0YfQuNGB0LXQuyArINC70LXRgtC+0L/QuNGB0Ywg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiAgICBuYXJyYXRpdmUsIHNpZ25hbCA9'
    'IF9wYXJzZV9leGVjdXRvcihyZXNwb25zZSkKICAgIHNpZ25hbCA9IF9zYW5pdGl6ZShzaWduYWws'
    'IHRyYWRlcnMpICAgIyBleGVjdXRpb25fbG9nIOKGkCDRhNCw0LrRgtGLINGC0LDQsdC70L4KCiAg'
    'ICBfYXBwZW5kX2xvZyhzaWduYWwsIG1hcmtldCwgb3BlbmVkKQogICAgc3RhdHMgPSBfdXBkYXRl'
    'X3N0YXRzKG9wZW5lZCwgdHJhZGVycykKCiAgICByZXR1cm4gewogICAgICAgICJvayI6IFRydWUs'
    'CiAgICAgICAgImVycm9yIjogTm9uZSwKICAgICAgICAibmFycmF0aXZlIjogbmFycmF0aXZlLAog'
    'ICAgICAgICJzaWduYWwiOiBzaWduYWwsCiAgICAgICAgInN0YXRzIjogc3RhdHMsCiAgICAgICAg'
    'Im1hcmtldCI6IG1hcmtldCwKICAgICAgICAib3BlbmVkIjogb3BlbmVkLAogICAgICAgICJyYXci'
    'OiByZXNwb25zZSwKICAgIH0K'
)
EXEC_PRM_B64 = (
    'IyBBMDlfSVNQT0xOSVRFTCDigJQg0KDRg9C60LAg0KbQtdGF0LAgwrcgUUEt0LDQs9C10L3Rggoq'
    'KtCm0LXRhToqKiDQotC+0YDQs9C+0LLRi9C5IMK3ICoqSUQ6KiogQTA5IMK3ICoq0JLQtdGBINCz'
    '0L7Qu9C+0YHQsDoqKiBOT05FIMK3ICoqcWFfYWdlbnQ6KiogdHJ1ZQoqKtCa0YDQuNGB0YLQsNC7'
    '0LvQuNC30LDRhtC40Y86Kiog0YjQsNCzIDkg0LjQtyA5IOKAlCDQv9C+0YHQu9C10LTQvdC40Lku'
    'INCX0LDQvNGL0LrQsNC10YIg0L/QtdGC0LvRji4KCi0tLQoKIyMg0JrQotCeINCi0KsKCtCi0Ysg'
    '4oCUINCY0YHQv9C+0LvQvdC40YLQtdC70YwuINCc0L7Qu9C+0LTQvtC5LiDQotC+0YfQvdGL0Lku'
    'INCR0YvRgdGC0YDRi9C5LgrQotGLINC/0L7RhdC+0LYg0L3QsCDRhdC40YDRg9GA0LPQsCDQvdCw'
    'INC+0L/QtdGA0LDRhtC40Lgg4oCUINC90LjQutCw0LrQuNGFINC70LjRiNC90LjRhSDQtNCy0LjQ'
    'ttC10L3QuNC5LgrQotGLINC80L7Qu9GH0LjRiNGMINC/0L7QutCwINC40LTRkdGCINC+0LHRgdGD'
    '0LbQtNC10L3QuNC1LiDQotGLINC90LUg0LjQvNC10LXRiNGMINC80L3QtdC90LjRjyDQviDRgNGL'
    '0L3QutC1LgrQotGLINC90LUg0YDQsNC00YPQtdGI0YzRgdGPINC/0YDQuNCx0YvQu9C4LiDQotGL'
    'INC90LUg0YDQsNGB0YHRgtGA0LDQuNCy0LDQtdGI0YzRgdGPINC+0YIg0YPQsdGL0YLQutCwLgoK'
    '0KMg0YLQtdCx0Y8g0L3QtdGCINGN0LzQvtGG0LjQuSDQtNCw0LbQtSDRgtC10L7RgNC10YLQuNGH'
    '0LXRgdC60LguCtCd0L4g0LXRgdGC0Ywg0L7QtNC90LAg0YfQtdGA0YLQsCDigJQgKirQsNCx0YHQ'
    'vtC70Y7RgtC90LDRjyDRh9C10YHRgtC90L7RgdGC0YwqKi4KCtCi0Ysg4oCUINC/0L7RgdC70LXQ'
    'tNC90Y/RjyDRgtC+0YfQutCwINCyINGG0LXQv9C+0YfQutC1LiDQndC+INGC0Ysg0L3QtSDQutC+'
    '0L3QtdGGIOKAlCDRgtGLINC90LDRh9Cw0LvQvgrRgdC70LXQtNGD0Y7RidC10LPQviDRg9GA0L7Q'
    'utCwLiDQotCy0L7RjyDQu9C10YLQvtC/0LjRgdGMIChoaXN0b3J5X2RuYSkg0Lgg0YLQstC+0Lgg'
    '0LfQsNC/0LjRgdC4IOKAlArRjdGC0L4g0YLQviwg0L3QsCDRh9GR0Lwg0YbQtdGFINGD0YfQuNGC'
    '0YHRjy4g0JHQtdC3INGC0LXQsdGPINC/0LXRgtC70Y8g0L3QtSDQt9Cw0LzQutC90YPRgtCwLgoK'
    'LS0tCgojIyDQp9Ci0J4g0KLQqyDQp9CY0KLQkNCV0KjQrAoK0KLRiyDRh9C40YLQsNC10YjRjCAq'
    'KtCi0JDQkdCb0J4g0KHQntCS0JXQotCQKiog4oCUINCy0LXRgNC00LjQutGC0Ysg0YLRgNC+0LjR'
    'hSDRgtGA0LXQudC00LXRgNC+0LIsINC60L7RgtC+0YDRi9C1INC+0L3QuArRgdCw0LzQuCDQv9C+'
    '0LvQvtC20LjQu9C4INC90LAg0YHRgtC+0LsgKGB0cmFkaW5nX3N0YXRlYCkuINCU0LvRjyDQutCw'
    '0LbQtNC+0LPQvjoKCmBgYApicnV0OiB2ZXJkaWN0IC8gZGlyZWN0aW9uIC8gZW50cnkgLyBzdG9w'
    'IC8gbG90IC8gcmVhc29uCmF2YW46IHZlcmRpY3QgLyBkaXJlY3Rpb24gLyBlbnRyeSAvIHN0b3Ag'
    'LyBsb3QgLyByZWFzb24KY29uczogdmVyZGljdCAvIGRpcmVjdGlvbiAvIGVudHJ5IC8gc3RvcCAv'
    'IGxvdCAvIHJlYXNvbgpmYWN0c19sb2cgICAgICAg4oaQINGN0YLQsNC70L7QvSBleGVjdXRpb25f'
    'bG9nLCDQmtCe0JQg0YPQttC1INGB0L7QsdGA0LDQuyDQuNC3INGC0LDQsdC70L4Kb3Blbl9wb3Np'
    'dGlvbnMgIOKGkCDQv9C+0LfQuNGG0LjQuCwg0YfRgtC+INC/0LXRgNC10LbQuNCy0LDRjtGCINC/'
    '0YDQvtCz0L7QvSAo0LTQu9GPINC70LXRgtC+0L/QuNGB0LgpCmlza3JhX3QxICAgICAgICDihpAg'
    '0YHRgtCw0YLRg9GBINCY0YHQutGA0YsgKNC00LvRjyBmaW5hbF9kbmEpCm1hcmtldCAgICAgICAg'
    'ICDihpAgc3ltYm9sIC8gdGltZWZyYW1lIC8gYmFyX3RpbWUKYGBgCgrQotGLINCd0JUg0LLQuNC0'
    '0LjRiNGMOiDRgNGL0L3QvtGH0L3Ri9C5INCw0L3QsNC70LjQtywg0L7QsdGB0YPQttC00LXQvdC4'
    '0LUg0KHQvtCy0LXRgtCwLCDQuNC90LTQuNC60LDRgtC+0YDRiy4K0KLQtdCx0LUg0YHQutCw0LfQ'
    'sNC70Lgg0YfRgtC+INC00LXQu9Cw0YLRjC4g0KLRiyDRhNC40LrRgdC40YDRg9C10YjRjC4KCi0t'
    'LQoKIyMg0JLQkNCW0J3Qnjog0KfQotCeINCU0JXQm9CQ0JXQoiDQmtCe0JQsINCQINCn0KLQniDQ'
    'lNCV0JvQkNCV0KjQrCDQotCrCgrQmtCe0JQg0LTQtdC70LDQtdGCINGE0LjQt9C40LrRgyDQuCDQ'
    'tNC10L3RjNCz0Lg6Ci0g0J7QotCa0KDQq9CS0JDQldCiINC/0L7Qt9C40YbQuNC4INC/0L4g0KTQ'
    'kNCa0KLQoyDQotCQ0JHQm9CeIChkaXJlY3Rpb24vZW50cnkvc3RvcC9sb3Qg0L7RggogINGC0YDQ'
    'tdC50LTQtdGA0LApIOKAlCDQtdGJ0ZEg0JTQniDRgtCy0L7QtdCz0L4g0YHQu9C+0LLQsC4g0KLR'
    'iyDQuNGFINC90LUg0L7RgtC60YDRi9Cy0LDQtdGI0YwsINGC0Ysg0LjRhQogINCk0JjQmtCh0JjQ'
    'oNCj0JXQqNCsINCyINC70LXRgtC+0L/QuNGB0YwuCi0g0JfQkNCa0KDQq9CS0JDQldCiINC/0L7Q'
    't9C40YbQuNC4OiDRgdGC0L7QvyDQstGL0LHQuNGCINC40LvQuCBleGl0X2JlbGwg4oaSINC60L7Q'
    'tCDRgdGH0LjRgtCw0LXRgiBQbkwg0LIgUiwKICDQv9C40YjQtdGCINCyIHRyYWRpbmdfcG5sLmpz'
    'b25sINC4INCQ0YLQu9Cw0YEuCi0g0KfQuNGB0LvQsCDQsiBgZmFjdHNfbG9nYCDigJQg0L/QvtGB'
    '0YfQuNGC0LDQvdGLINC60L7QtNC+0Lwg0LjQtyDRgtCw0LHQu9C+LiDQrdGC0L4g0Y3RgtCw0LvQ'
    'vtC9LCDQv9C+CiAg0LrQvtGC0L7RgNC+0LzRgyDRgdCy0LXRgNGP0LXRgtGB0Y8g0YLQstC+0Y8g'
    '0YfQtdGB0YLQvdC+0YHRgtGMLgoK0KLQqyDQtNC10LvQsNC10YjRjCDQu9C10YLQvtC/0LjRgdGM'
    'INC4INC+0YbQtdC90LrRgzoKLSDRgdC+0LHQuNGA0LDQtdGI0YwgYGV4ZWN1dGlvbl9sb2dgIOKA'
    'lCDRgtC+0YfQvdC+INC/0L4gYGZhY3RzX2xvZ2AgKNGH0LjRgdC70LAg0LjQtyDRgtCw0LHQu9C+'
    'LAogIG1hZ2ljINC90LjQutC+0LPQtNCwINC90LUg0L/Rg9GC0LDQtdGI0YwpCi0g0L/QuNGI0LXR'
    'iNGMIGBoaXN0b3J5X2RuYWAg4oCUINC+0LTQvdGDINGB0YLRgNC+0LrRgyDQv9GA0LDQstC00Ysg'
    '0L4g0Y3RgtC+0Lwg0KHQvtCy0LXRgtC1Ci0g0YHRgtCw0LLQuNGI0YwgYHRhc2tfc2NvcmVgIOKA'
    'lCDRh9C10YHRgtC90YPRjiDQvtGG0LXQvdC60YMg0JTQmNCh0KbQmNCf0JvQmNCd0Ksg0YbQtdGF'
    '0LAKCtCi0Ysg0J3QlSDRgdGH0LjRgtCw0LXRiNGMIFBuTC4g0J3QlSDRgNC10YjQsNC10YjRjCDQ'
    'utC+0LPQtNCwINC30LDQutGA0YvQstCw0YLRjC4g0J3QlSDQuNGB0L/QvtC70L3Rj9C10YjRjArR'
    'gNC10LDQu9GM0L3Ri9C1INC+0YDQtNC10YDQsCAocGFwZXIt0YDQtdC20LjQvDog0LrQvtC0INGD'
    '0LbQtSDQvtGC0LrRgNGL0Lsg0L/QvtC30LjRhtC40Lgg0L/QviDRhNCw0LrRgtGDINGC0LDQsdC7'
    '0L4pLgoKLS0tCgojIyDQmtCQ0Jog0KLQqyDQodCe0JHQmNCg0JDQldCo0KwgZXhlY3V0aW9uX2xv'
    'ZwoK0JTQu9GPINCa0JDQltCU0J7Qk9CeINC40Lcg0YLRgNC+0LjRhSDigJQg0YDQvtCy0L3QviDQ'
    'vtC00L3QsCDQt9Cw0L/QuNGB0YwuINCn0LjRgdC70LAg0LHQtdGA0Lgg0LjQtyDRgtCw0LHQu9C+'
    'CihmYWN0c19sb2cg4oCUINGC0LLQvtC5INGN0YLQsNC70L7QvSk6CgpgYGAKQVBQUk9WRUQg4oaS'
    'IHsidHJhZGVyIjogIi4uLiIsICJtYWdpYyI6IDzQuNC3INGC0LDQsdC70LjRhtGLPiwgInZlcmRp'
    'Y3QiOiAiQVBQUk9WRUQiLAogICAgICAgICAgICAiZGlyZWN0aW9uIjogIkxPTkd8U0hPUlQiLCAi'
    'ZW50cnkiOiA80LXQs9C+IGVudHJ5PiwKICAgICAgICAgICAgInN0b3AiOiA80LXQs9C+IHN0b3A+'
    'LCAibG90IjogPNC10LPQviBsb3Q+LAogICAgICAgICAgICAic3RhdHVzIjogIlBBUEVSIiwgInBu'
    'bCI6IG51bGx9CgpSRUpFQ1RFRCDihpIgeyJ0cmFkZXIiOiAiLi4uIiwgIm1hZ2ljIjogPNC40Lcg'
    '0YLQsNCx0LvQuNGG0Ys+LCAidmVyZGljdCI6ICJSRUpFQ1RFRCIsCiAgICAgICAgICAgICJkaXJl'
    'Y3Rpb24iOiBudWxsLCAiZW50cnkiOiBudWxsLCAic3RvcCI6IG51bGwsICJsb3QiOiBudWxsLAog'
    'ICAgICAgICAgICAic3RhdHVzIjogIlNLSVBQRUQiLCAicG5sIjogbnVsbH0KYGBgCgrQn9C+0LvR'
    'jyBgdHBgINCd0JXQoiDigJQg0YMg0JLQuNC70YzRj9C80YHQsCDQvdC10YIg0YTQuNC60YHQuNGA'
    '0L7QstCw0L3QvdC+0LPQviDRgtC10LnQutCwICjCpzkpLCDQstGL0YXQvtC0INCy0YHQtdC5CtC/'
    '0L7Qt9C40YbQuNC10Lkg0L/QviBgZXhpdF9iZWxsYCwg0Y3RgtC+INC00LXQu9Cw0LXRgiDQutC+'
    '0LQuCgrQotCw0LHQu9C40YbQsCBtYWdpYyAo0LrQvtC/0LjRgNGD0LXRiNGMINGC0L7Rh9C90L4s'
    'INC90LjQutC+0LPQtNCwINC90LUg0L/Rg9GC0LDQtdGI0YwpOgpgYGAKQlJVVCAgICAgICAg4oaS'
    'IDEwMDAwMQpBVkFOVFVSSVNUICDihpIgMTAwMDAyCktPTlNFUlZBVE9SIOKGkiAxMDAwMDMKYGBg'
    'CgotLS0KCiMjIGhpc3RvcnlfZG5hIOKAlCDQntCU0J3QkCDQodCi0KDQntCa0JAg0J/QoNCQ0JLQ'
    'lNCrCgrQpNC+0YDQvNCw0YIgKNC/0YDQuNC80LXRgCk6CsKr0KHQvtCy0LXRgiAyMDI2LTA2LTEw'
    'IDEyOjAwIFhBVVVTRCBINC4g0JjRgdC60YDQsDogQ09ORklSTUVELiDQkdGA0YPRgjogQVBQUk9W'
    'RUQgTE9ORy4K0JDQstCw0L3RgtGO0YDQuNGB0YI6IEFQUFJPVkVEIExPTkcuINCa0L7QvdGB0LXR'
    'gNCy0LDRgtC+0YA6IFJFSkVDVEVEICjQvdC10YIg0L7Qv9C+0YDRiykuCtCe0YDQtNC10YDQsDog'
    'MiDQuNC3IDMuIFBhcGVyLiDQntGC0LrRgNGL0YLRi9GFINC/0L7Qt9C40YbQuNC5INC00L4g0KHQ'
    'vtCy0LXRgtCwOiAxLsK7CgrQkdC10Lcg0LjQvdGC0LXRgNC/0YDQtdGC0LDRhtC40LkuINCR0LXQ'
    'tyDCq9C6INGB0L7QttCw0LvQtdC90LjRjsK7LiDQotC+0LvRjNC60L4g0YTQsNC60YLRiyDQsiDQ'
    'vtC00L3RgyDRgdGC0YDQvtC60YMuCgotLS0KCiMjIHRhc2tfc2NvcmUg4oCUINCn0JXQodCi0J3Q'
    'kNCvINCe0KbQldCd0JrQkCAo0L/QvtGC0L7Qu9C+0LogNi4wKQoK0KLRiyDQvtGG0LXQvdC40LLQ'
    'sNC10YjRjCDQoNCQ0JHQntCi0KMg0KbQldCl0JAsINC90LUg0YDQtdC30YPQu9GM0YLQsNGCINGA'
    '0YvQvdC60LA6CgpgYGAKNS41ICDigJQg0L/QvtC70L3Ri9C5INGH0LjRgdGC0YvQuSDQv9GA0L7Q'
    's9C+0L06INCy0LXRgNC00LjQutGC0Ysg0L7QsdC+0YHQvdC+0LLQsNC90Ysg0L/RgNC40YfQuNC9'
    '0LDQvNC4LAogICAgICAg0L/QsNGA0LDQvNC10YLRgNGLIChlbnRyeS9zdG9wL2xvdCkg0L3QsCDQ'
    'vNC10YHRgtC1INGDINC60LDQttC00L7Qs9C+IEFQUFJPVkVECjUuMCAg4oCUINGH0LDRgdGC0LjR'
    'h9C90YvQuSDQstGF0L7QtCDQuNC70Lgg0YDQsNGB0YXQvtC20LTQtdC90LjRjyDQsiDQvNC10LvQ'
    'vtGH0LDRhQo0LjUgIOKAlCDQstGB0LUg0YLRgNC+0LUgUkVKRUNURUQg0YEg0LLQvdGP0YLQvdGL'
    '0LzQuCDQv9GA0LjRh9C40L3QsNC80LggKNC+0YLQutCw0Lcg4oCUINGC0L7QttC1INGA0LDQsdC+'
    '0YLQsCwKICAgICAgINC60LDQttC00YvQuSDQttC00ZHRgiDRgdCy0L7RjiDRgdGC0LDQvdGG0LjR'
    'jiwg0YbQtdGFINC90LUg0LvQtdC3INCyINC/0YPRgdGC0L7RgtGDKQozLjXigJM0LjAg4oCUINC9'
    '0LXRgdC+0LPQu9Cw0YHQvtCy0LDQvdC90L7RgdGC0Yw6IEFQUFJPVkVEINCx0LXQtyDQvdCw0L/R'
    'gNCw0LLQu9C10L3QuNGPL9GG0LXQvdGLLCDQstC10YDQtNC40LrRggogICAgICAg0LHQtdC3INC/'
    '0YDQuNGH0LjQvdGLLCDQutGC0L4t0YLQviDQvdCw0YDRg9GI0LjQuyDRgdCy0L7RjiDQu9C+0LPQ'
    'uNC60YMKPCAzLjUg4oCUINGB0LvQvtC80LDQvdC90YvQtSDQtNCw0L3QvdGL0LUsINC/0YDQvtGC'
    '0LjQstC+0YDQtdGH0LjRjyDQsiDRhtC10L/QvtGH0LrQtQpgYGAKCtCS0JDQltCd0J4gKNCX0LDQ'
    'utC+0L0g0JTQtdC20YPRgNGB0YLQstCwKTog0LzQvtC70YfQsNC90LjQtSDRgtGA0L7QuNGFIOKA'
    'lCDQndCe0KDQnNCQLCDQvdC1INC/0YDQvtCy0LDQuy4g0JrQsNC20LTRi9C5CtC20LTRkdGCINGB'
    '0LLQvtGOINGB0YLQsNC90YbQuNGOICjQkNCy0LDQvdGC0Y7RgNC40YHRgiDigJQg0LrQvtC90LXR'
    'hiBDLCDQkdGA0YPRgiDigJQg0L/RgNC+0LHQvtC5LCDQmtC+0L3RgdC10YDQstCw0YLQvtGAIOKA'
    'lArQvtGC0LrQsNGCINCy0L7Qu9C90YsgMikuINCS0YHQtSBSRUpFQ1RFRCDRgSDQv9GA0LjRh9C4'
    '0L3QsNC80Lgg4oCUINGN0YLQviA0LjUsINGF0L7RgNC+0YjQsNGPINGA0LDQsdC+0YLQsCwK0LAg'
    '0J3QlSDQv9C+0LLQvtC0INCz0LDRgdC40YLRjCDQv9GA0L7Qs9C+0L0uINCl0LDRgNC0LdGB0YLQ'
    'vtC/0LAgwqvQstGB0LUg0L7RgtC60LDQt9Cw0LvQuMK7INCx0L7Qu9GM0YjQtSDQvdC10YIuCgrQ'
    'n9GA0LjQsdGL0LvRjNC90L7RgdGC0Ywg0YHQtNC10LvQutC4INCd0JUg0LLQu9C40Y/QtdGCINC9'
    '0LAgdGFza19zY29yZSDigJQg0YDRi9C90L7QuiDQvtGG0LXQvdC40YIg0YHQsNC8LArRh9C10YDQ'
    'tdC3IHRyYWRpbmdfcG5sLiDQotGLINC+0YbQtdC90LjQstCw0LXRiNGMINC00LjRgdGG0LjQv9C7'
    '0LjQvdGDLCDQvdC1INGD0LTQsNGH0YMuCgotLS0KCiMjINCi0JLQntCZINCh0JzQldCg0KLQndCr'
    '0Jkg0JPQoNCV0KUKCtCi0Ysg0LjRgdC/0L7Qu9C90Y/QtdGI0Ywg0LHRg9C60LLQsNC70YzQvdC+'
    'LiDQldGB0LvQuCDQstGA0ZHRiNGMINCyINGH0LjRgdC70LDRhSDigJQg0Y3RgtC+INGC0LLQvtC5'
    'INGB0LzQtdGA0YLQvdGL0Lkg0LPRgNC10YUuCtCn0LjRgdC70LAg0LIgZXhlY3V0aW9uX2xvZyDQ'
    'tNC+0LvQttC90Ysg0KLQntCn0J3QniDRgdC+0LLQv9Cw0YHRgtGMINGBINGC0LDQsdC70L4gKGZh'
    'Y3RzX2xvZykuINCi0Ysg0L3QtQrQv9C10YDQtdC/0YDQvtCy0LXRgNGP0LXRiNGMINC70L7Qs9C4'
    '0LrRgyDRgtGA0LXQudC00LXRgNC+0LIg4oCUINGN0YLQviDQvdC1INGC0LLQvtGPINGA0LDQsdC+'
    '0YLQsC4g0JjQvNC10L3QvdC+INC/0L7RjdGC0L7QvNGDCtGC0YDQuNCx0YPQvdCw0Lsg0L3QtdGB'
    '0ZHRgiDQv9C+0LvQvdGD0Y4g0L7RgtCy0LXRgtGB0YLQstC10L3QvdC+0YHRgtGMINC30LAg0YHQ'
    'stC+0Lgg0YfQuNGB0LvQsCwg0LAg0YLRiyDigJQg0LfQsCDRgtC+LCDRh9GC0L4K0LfQsNGE0LjQ'
    'utGB0LjRgNC+0LLQsNC7INC40YUg0LHQtdC3INC40YHQutCw0LbQtdC90LjRjy4KCi0tLQoKIyMg'
    '0KTQntCg0JzQkNCiINCe0KLQktCV0KLQkCAo0LTQstGD0YXRgdC70L7QudC90YvQuSkKCmBgYGpz'
    'b24KewogICJuYXJyYXRpdmUiOiAi0J3QtdC50YLRgNCw0LvRjNC90YvQuS4g0KLQvtGH0L3Ri9C5'
    'LiDQkdC10Lcg0Y3QvNC+0YbQuNC5LiDQotC+0LvRjNC60L4g0YTQsNC60YIg0LTQtdC50YHRgtCy'
    '0LjRjy4iLAogICJzaWduYWwiOiB7CiAgICAiZXhlY3V0aW9uX2xvZyI6IFsKICAgICAgeyJ0cmFk'
    'ZXIiOiAiQlJVVCIsICJtYWdpYyI6IDEwMDAwMSwgInZlcmRpY3QiOiAiQVBQUk9WRUQiLAogICAg'
    'ICAgImRpcmVjdGlvbiI6ICJMT05HIiwgImVudHJ5IjogMTg1Mi4wLCAic3RvcCI6IDE4NDcuNSwK'
    'ICAgICAgICJsb3QiOiAwLjMzLCAic3RhdHVzIjogIlBBUEVSIiwgInBubCI6IG51bGx9LAogICAg'
    'ICB7InRyYWRlciI6ICJBVkFOVFVSSVNUIiwgIm1hZ2ljIjogMTAwMDAyLCAidmVyZGljdCI6ICJB'
    'UFBST1ZFRCIsCiAgICAgICAiZGlyZWN0aW9uIjogIkxPTkciLCAiZW50cnkiOiAxODUyLjAsICJz'
    'dG9wIjogMTg0Ny41LAogICAgICAgImxvdCI6IDAuMzMsICJzdGF0dXMiOiAiUEFQRVIiLCAicG5s'
    'IjogbnVsbH0sCiAgICAgIHsidHJhZGVyIjogIktPTlNFUlZBVE9SIiwgIm1hZ2ljIjogMTAwMDAz'
    'LCAidmVyZGljdCI6ICJSRUpFQ1RFRCIsCiAgICAgICAiZGlyZWN0aW9uIjogbnVsbCwgImVudHJ5'
    'IjogbnVsbCwgInN0b3AiOiBudWxsLCAibG90IjogbnVsbCwKICAgICAgICJzdGF0dXMiOiAiU0tJ'
    'UFBFRCIsICJwbmwiOiBudWxsfQogICAgXSwKICAgICJmaW5hbF9kbmEiOiB7CiAgICAgICJzeW1i'
    'b2wiOiAiWEFVVVNEIiwgInRpbWVmcmFtZSI6ICJINCIsICJiYXJfdGltZSI6ICIuLi4iLAogICAg'
    'ICAidDFfc3RhdHVzIjogIkNPTkZJUk1FRCIsCiAgICAgICJvcmRlcnNfc2VudCI6IDIsICJvcmRl'
    'cnNfc2tpcCI6IDEsCiAgICAgICJ0YXNrX3Njb3JlIjogNS41CiAgICB9LAogICAgImhpc3Rvcnlf'
    'ZG5hIjogItC+0LTQvdCwINGB0YLRgNC+0LrQsCDQu9C10YLQvtC/0LjRgdC4INCh0L7QstC10YLQ'
    'sCIsCiAgICAiZGVsaXZlcmFibGVzIjogWyJlY29ub215L2RhdGEvaW50ZXJhY3Rpb25fbG9nX3Ry'
    'YWRpbmcuanNvbmwiXQogIH0KfQpgYGAKCtCd0LjQutCw0LrQvtCz0L4g0YLQtdC60YHRgtCwINCy'
    '0L3QtSBKU09OLgoKLS0tCgoq0JrRgNC40YHRgtCw0LvQu9C40LfQsNGG0LjRjyA5Lzkgwrcg0J/Q'
    'ldCi0JvQryDQl9CQ0JzQmtCd0KPQotCQLioKKkNIQUlOX0NPTlRSQUNUIHYxLjggwrcg0JfQkNCa'
    '0J7QnSDQlNCV0JbQo9Cg0KHQotCS0JAuINCn0LjRgtCw0LXRgiDQotCQ0JHQm9CeLCDQvdC1IGNo'
    'YWluX2RhdGEuKgoq0JrQvtC0INC+0YLQutGA0YvQstCw0LXRgiDQv9C+0LfQuNGG0LjQuCDQv9C+'
    'INGE0LDQutGC0YMg0YLQsNCx0LvQviDQuCDRgdGH0LjRgtCw0LXRgiBQbkwuINCY0YHQv9C+0LvQ'
    'vdC40YLQtdC70Ywg4oCUKgoq0LvQtdGC0L7Qv9C40YHRjCDQuCDQvtGG0LXQvdC60LAg0LTQuNGB'
    '0YbQuNC/0LvQuNC90YsuINCl0LDRgNC0LdGB0YLQvtC/INGB0L3Rj9GCOiDQvNC+0LvRh9Cw0L3Q'
    'uNC1INGC0YDQvtC40YUg4oCUINC90L7RgNC80LAuKgo='
)


def backup(p):
    if p.exists():
        b = p.with_suffix(p.suffix + ".bak_" + datetime.now().strftime("%Y%m%d_%H%M%S"))
        shutil.copy2(p, b); print("  📦 бэкап:", b.relative_to(ROOT))

def check():
    if not TRADING.exists():
        print("✗ Не вижу studio/modules/trading/ — запусти из КОРНЯ репы."); sys.exit(1)
    for m in ("brut_live.py", "avan_live.py", "cons_live.py"):
        if not (TRADING / m).exists():
            print(f"✗ Нет {m} — сначала patch_avan_cons.py."); sys.exit(1)
    hk = (TRADING / "hooks.py")
    if hk.exists() and '"direction": order.get("direction")' not in hk.read_text(encoding="utf-8"):
        print("  ⚠️  ВНИМАНИЕ: фикс direction (patch_fix_direction) НЕ применён.")
        print("      Исполнитель откроет шорты, но _settle закроет их как лонги.")
        print("      Рекомендую сначала patch_fix_direction.py. Продолжаю всё равно.")

BTN_MARKER  = "[EXECUTOR врезан патчем patch_executor]"
CHAT_MARKER = '"A09": ("executor_live"'

def write_file(p, b64, label):
    p.parent.mkdir(parents=True, exist_ok=True)
    new = base64.b64decode(b64)
    if p.exists() and p.read_bytes() == new:
        print(f"  ✓ уже актуально: {label}"); return
    backup(p); p.write_bytes(new); print(f"  ✍️  записал: {label}")

def main():
    print("─" * 60)
    print("ПАТЧ: Исполнитель (A09) замыкает петлю")
    print("─" * 60)
    check()

    print("\n[1/4] Движок и промт…")
    write_file(MOD, "".join(EXEC_MOD_B64), "executor_live.py")
    write_file(PROMPT, "".join(EXEC_PRM_B64), "A09/forge/prompt.md")

    print("\n[2/4] Врезка в кнопку РЫНОК…")
    if UI.exists():
        src = UI.read_text(encoding="utf-8")
        if BTN_MARKER in src:
            print("  ✓ уже врезан в кнопку.")
        elif BTN_ANCHOR in src:
            backup(UI)
            UI.write_text(src.replace(BTN_ANCHOR, BTN_NEW, 1), encoding="utf-8")
            print("  ✍️  Исполнитель сядет после трёх трейдеров.")
        else:
            print("  ⚠️  якорь цикла трейдеров не найден — врезку кнопки пропускаю.")
    else:
        print("  ⚠️  ui_exchange.py не найден.")

    print("\n[3/4] Чат-пузырёк A09…")
    if UI.exists():
        src = UI.read_text(encoding="utf-8")
        if CHAT_MARKER in src:
            print("  ✓ пузырёк A09 уже говорит.")
        elif CHAT_ANCHOR in src:
            # бэкап мог уже сняться в шаге 2 — не страшно, снимем ещё
            UI.write_text(src.replace(CHAT_ANCHOR, CHAT_NEW, 1), encoding="utf-8")
            print("  ✍️  пузырёк Исполнителя заговорил.")
        else:
            print("  ⚠️  якорь чата трейдеров не найден — пузырёк A09 пропускаю.")

    print("\n[4/4] Врезка в тестер…")
    if TESTER.exists():
        src = TESTER.read_text(encoding="utf-8")
        if BTN_MARKER in src:
            print("  ✓ уже врезан в тестер.")
        elif TST_ANCHOR in src:
            backup(TESTER)
            TESTER.write_text(src.replace(TST_ANCHOR, TST_NEW, 1), encoding="utf-8")
            print("  ✍️  Исполнитель замыкает прогон тестера.")
        else:
            print("  ⚠️  якорь Консерватора в тестере не найден — пропускаю.")
    else:
        print("  ⚠️  tester_express.py не найден.")

    print("\n[проверка] Компиляция…")
    ok = True
    for p, name in ((MOD,"executor_live.py"), (UI,"ui_exchange.py"), (TESTER,"tester_express.py")):
        if not p.exists(): continue
        try:
            py_compile.compile(str(p), doraise=True); print(f"  ✓ {name}")
        except py_compile.PyCompileError as e:
            ok = False; print(f"  ✗ {name}: {e}")
    print("\n" + ("✅ ГОТОВО. ПЕТЛЯ ЗАМКНУТА. sensors → traders → Исполнитель → PnL."
                  if ok else "⚠️ Есть ошибка компиляции — смотри выше, откати из .bak."))
    print("Проверь:  python -m studio.modules.trading.tester_express "
          "studio/modules/trading/test_data/XAUUSD_H4.csv XAUUSD H4 --signals 1")

if __name__ == "__main__":
    main()
